version: '2'
plugins:
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
exclude_paths:
  - '.github/'
  - 'assets/'
  - 'docs/'
  - 'packages/**/tests/'
  - 'integrations/'
  - 'integration/'
  - 'tools/'
  - 'cypress/'
  - 'jest.config.js'
ratings:
  paths:
    - 'packages/**/**.ts'
